-- Puntos FourMaster generados automaticamente con geocodificacion Nominatim
-- Ejecutar en Supabase SQL Editor o via: npx prisma db execute --stdin < scripts/fourmaster-puntos.sql

DO $$
DECLARE v_empresa_id TEXT;
BEGIN
  SELECT id INTO v_empresa_id FROM empresas WHERE LOWER(nombre) LIKE '%four%master%' OR LOWER(slug) = 'four-master' LIMIT 1;
  IF v_empresa_id IS NULL THEN RAISE EXCEPTION 'Empresa FourMaster no encontrada'; END IF;

  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'ASCENSORES SERVAS - ALSINA 901', -34.60882, -58.37415, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'ASCENSORES SERVAS - ALSINA 901');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - HUMAHUACA 4676', -34.6009726, -58.430717, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - HUMAHUACA 4676');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CULLEN 5140', -34.5732542, -58.4883909, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CULLEN 5140');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CONDE 1526', -34.5706356, -58.4626032, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CONDE 1526');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'EXPRESO EL DORADO - SARAZA 5653', -34.6721146, -58.4811687, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'EXPRESO EL DORADO - SARAZA 5653');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - BENITEZ JULIO OMAR 4243', -34.6626728, -58.4684195, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - BENITEZ JULIO OMAR 4243');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'VTV CAISA - LARRAZABAL 1861', -34.6566269, -58.4967941, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'VTV CAISA - LARRAZABAL 1861');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'SPORT CLUB - RIVADAVIA 10652', -34.6374678, -58.4997729, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'SPORT CLUB - RIVADAVIA 10652');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - SARMIENTO 2274', -34.6061488, -58.3989416, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - SARMIENTO 2274');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - NUNEZ 1567', -34.5456787, -58.4596519, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - NUNEZ 1567');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CARLOS CALVO 3233', -34.6229764, -58.4121909, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CARLOS CALVO 3233');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - INDEPENDENCIA 3982', -34.6214928, -58.4218779, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - INDEPENDENCIA 3982');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - BILLINGHURST 1034', -34.5825891, -58.4032732, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - BILLINGHURST 1034');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CHACABUCO 1028', -34.6183321, -58.3758568, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CHACABUCO 1028');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'EMPRESA WCS - FLORIDA 981', -34.59956, -58.37363, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'EMPRESA WCS - FLORIDA 981');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'EMPRESA KIDSCORP - ARCOS 2215', -34.5591887, -58.4547792, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'EMPRESA KIDSCORP - ARCOS 2215');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'SMART SEGUROS - ALVEAR 1563', -34.6542754, -58.564664, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'SMART SEGUROS - ALVEAR 1563');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'ESTUDIO VALLI - AV. DE MAYO 432', -34.6447378, -58.5647018, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'ESTUDIO VALLI - AV. DE MAYO 432');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - TACUARI 305', -34.6489135, -58.5642069, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - TACUARI 305');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - SAAVEDRA 233', -34.6478179, -58.5631142, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - SAAVEDRA 233');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - MARIANO MORENO 215', -34.642257, -58.5626548, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - MARIANO MORENO 215');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - MEDRANO 34', -34.6430379, -58.5773838, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - MEDRANO 34');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - BARCALA 564', -34.6381839, -58.5576368, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - BARCALA 564');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - VIAMONTE 333', -34.6428511, -58.5561773, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - VIAMONTE 333');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - ALFREDO PALACIOS 80', -34.640787, -58.5526201, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - ALFREDO PALACIOS 80');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - SARMIENTO 53', -34.6429486, -58.5616031, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - SARMIENTO 53');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - ALVAREZ JONTE 362', -34.6397921, -58.5685839, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - ALVAREZ JONTE 362');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - BELGRANO 269', -34.642114, -58.5680472, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - BELGRANO 269');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - ESPORA 33', -34.6439895, -58.5622471, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - ESPORA 33');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'DISTRIBUIDORA NINO - BOLIVAR 781', -34.6475812, -58.5626672, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'DISTRIBUIDORA NINO - BOLIVAR 781');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CASTELLI 65', -34.644811, -58.5615231, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CASTELLI 65');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - SAN MARTIN 2823', -34.6641299, -58.5393314, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - SAN MARTIN 2823');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'SADEMEC - DR. REBIZZO 4728', -34.6132364, -58.5630427, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'SADEMEC - DR. REBIZZO 4728');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CHILE 1709', -34.6614515, -58.5913446, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CHILE 1709');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - GARIBALDI 2055', -34.655513, -58.5831677, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - GARIBALDI 2055');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'RAME PRODUCTOS QUIMICOS - AV. BUFANO 1089', -34.6796571, -58.5843368, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'RAME PRODUCTOS QUIMICOS - AV. BUFANO 1089');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - PERON 1044', -34.664168, -58.5730027, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - PERON 1044');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - AV. RIVADAVIA 15760', -34.6443517, -58.5877739, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - AV. RIVADAVIA 15760');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - PRES. PERON 1370', -34.6373381, -58.5844919, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - PRES. PERON 1370');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - SAN LORENZO 1149', -34.6526185, -58.6008468, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - SAN LORENZO 1149');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'TIENDA VEGGIE - VALENTIN GOMEZ 577', -34.6385999, -58.6147218, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'TIENDA VEGGIE - VALENTIN GOMEZ 577');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - CARLOS TEJEDOR 1275', -34.6442363, -58.5916021, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - CARLOS TEJEDOR 1275');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'GIM GLADIADOR - RIVADAVIA 16482', -34.6465058, -58.5964179, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'GIM GLADIADOR - RIVADAVIA 16482');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - M. DE ANDREA 77', -34.6435822, -58.5920515, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - M. DE ANDREA 77');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - RODRIGUEZ PENA 2060', -34.6015115, -58.5481485, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - RODRIGUEZ PENA 2060');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'OFICINAS MARAZZI - PEREDO 433', -34.6323462, -58.6824159, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'OFICINAS MARAZZI - PEREDO 433');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONDOMINIO - LA PIALADA 3618', -34.6236185, -58.706379, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONDOMINIO - LA PIALADA 3618');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'EMPRESA NORNEST - MENDEZ DE ANDES 1759', -34.6988687, -58.6272545, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'EMPRESA NORNEST - MENDEZ DE ANDES 1759');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - JUJUY 958', -34.6729073, -58.573006, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - JUJUY 958');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - ENTRE RIOS 3443', -34.6799502, -58.5554886, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - ENTRE RIOS 3443');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - ENTRE RIOS 2942', -34.6756513, -58.5610037, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - ENTRE RIOS 2942');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - AV. SAN MARTIN 2665', -34.6065681, -58.5621851, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - AV. SAN MARTIN 2665');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - WENCESLAO DE TATA 4664', -34.6015051, -58.5548046, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - WENCESLAO DE TATA 4664');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'OUT SOURCE - AV. GAONA 4379', -34.6345784, -58.5501908, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'OUT SOURCE - AV. GAONA 4379');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'NEW PET - SANTIAGO DE LINIERS 3836', -34.6338576, -58.5408631, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'NEW PET - SANTIAGO DE LINIERS 3836');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'DISTRIBUIDORA GROW - RICHIERI 4543', -34.6265283, -58.5420777, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'DISTRIBUIDORA GROW - RICHIERI 4543');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'SUELAS LEAL - SAN PEDRO 1949', -34.6934172, -58.5337588, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'SUELAS LEAL - SAN PEDRO 1949');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONALIA - MONTENEGRO 1198', -34.7020078, -58.5252727, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONALIA - MONTENEGRO 1198');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'PADILUM - PRESIDENTE PERON 3045', -34.6352142, -58.6049949, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'PADILUM - PRESIDENTE PERON 3045');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - BELGRANO 384', -34.6526469, -58.6211245, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - BELGRANO 384');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - SANTA FE 980', -34.6559468, -58.6223586, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - SANTA FE 980');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CONSORCIO - BOATTI 264', -34.6513222, -58.6161565, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CONSORCIO - BOATTI 264');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'ALCAP - CAAGUAZU 421', -34.6856606, -58.5037176, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'ALCAP - CAAGUAZU 421');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'CREATIV - PARQUE IND. SIPLA', -34.6173471, -58.9503302, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'CREATIV - PARQUE IND. SIPLA');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'KYC - TUPAC AMARU 550', -34.6140248, -58.8272039, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'KYC - TUPAC AMARU 550');
  INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) SELECT gen_random_uuid()::text, v_empresa_id, 'KYC - AV. ZAPIOLA 1148', -34.637127, -58.7420269, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW() WHERE NOT EXISTS (SELECT 1 FROM puntos_fichaje WHERE empresa_id = v_empresa_id AND nombre = 'KYC - AV. ZAPIOLA 1148');
END $$;

-- âš ï¸ Puntos NO geocodificados (coordenadas en 0,0 â€” corregir manualmente):
  -- INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) VALUES (gen_random_uuid()::text, (SELECT id FROM empresas WHERE LOWER(slug) = 'four-master' LIMIT 1), 'CONSORCIO - COLPAYO 368', 0, 0, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW());
  -- INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) VALUES (gen_random_uuid()::text, (SELECT id FROM empresas WHERE LOWER(slug) = 'four-master' LIMIT 1), 'CONSORCIO - COLPAYO 378/380', 0, 0, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW());
  -- INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) VALUES (gen_random_uuid()::text, (SELECT id FROM empresas WHERE LOWER(slug) = 'four-master' LIMIT 1), 'CONSORCIO - ZUBIAUR 4302', 0, 0, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW());
  -- INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) VALUES (gen_random_uuid()::text, (SELECT id FROM empresas WHERE LOWER(slug) = 'four-master' LIMIT 1), 'EXACTKABEL - SOURINGES 1408', 0, 0, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW());
  -- INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) VALUES (gen_random_uuid()::text, (SELECT id FROM empresas WHERE LOWER(slug) = 'four-master' LIMIT 1), 'CONSORCIO - PERDRIEL 5358', 0, 0, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW());
  -- INSERT INTO puntos_fichaje (id, empresa_id, nombre, latitud, longitud, radio_metros, qr_token, operaciones_token, activo, descanso_activo, created_at, updated_at) VALUES (gen_random_uuid()::text, (SELECT id FROM empresas WHERE LOWER(slug) = 'four-master' LIMIT 1), 'ANIXTER - MARCOS SASTRE 1712', 0, 0, 100, gen_random_uuid()::text, gen_random_uuid()::text, true, false, NOW(), NOW());
